/**
 * Dockerfile Generator
 * 
 * Generates a Dockerfile that recreates the exact project state
 * at the start of a trajectory. Anyone can build this image and
 * be at the exact point where the trajectory began.
 */

import { readFile, access } from "node:fs/promises";
import { join } from "node:path";

export interface DockerfileConfig {
	repoUrl: string;
	commitSha: string;
	language: string;
	testCommand: string;
	
	// Optional overrides
	baseImage?: string;
	extraDeps?: string[];
	setupCommands?: string[];
}

export interface GeneratedDockerfile {
	dockerfile: string;
	dockerignore: string;
	readme: string;
}

interface LanguageSpec {
	baseImage: string;
	depFiles: string[];
	installCmd: string;
	testCmd: string;
	runtimeDeps?: string[];
}

const LANGUAGE_SPECS: Record<string, LanguageSpec> = {
	python: {
		baseImage: "python:3.11-slim",
		depFiles: ["requirements.txt", "pyproject.toml", "setup.py", "setup.cfg"],
		installCmd: `
# Install dependencies
COPY requirements.txt* pyproject.toml* setup.py* setup.cfg* ./
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
RUN if [ -f pyproject.toml ]; then pip install --no-cache-dir -e .; fi
`,
		testCmd: "pytest",
		runtimeDeps: ["git"],
	},
	
	typescript: {
		baseImage: "node:20-slim",
		depFiles: ["package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml"],
		installCmd: `
# Install dependencies
COPY package*.json yarn.lock* pnpm-lock.yaml* ./
RUN if [ -f package-lock.json ]; then npm ci; \\
    elif [ -f yarn.lock ]; then yarn install --frozen-lockfile; \\
    elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && pnpm install --frozen-lockfile; \\
    else npm install; fi
`,
		testCmd: "npm test",
		runtimeDeps: ["git"],
	},
	
	javascript: {
		baseImage: "node:20-slim",
		depFiles: ["package.json", "package-lock.json", "yarn.lock"],
		installCmd: `
# Install dependencies  
COPY package*.json yarn.lock* ./
RUN if [ -f package-lock.json ]; then npm ci; \\
    elif [ -f yarn.lock ]; then yarn install --frozen-lockfile; \\
    else npm install; fi
`,
		testCmd: "npm test",
		runtimeDeps: ["git"],
	},
	
	rust: {
		baseImage: "rust:1.75-slim",
		depFiles: ["Cargo.toml", "Cargo.lock"],
		installCmd: `
# Cache dependencies
COPY Cargo.toml Cargo.lock* ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo fetch
RUN rm -rf src
`,
		testCmd: "cargo test",
		runtimeDeps: ["git", "pkg-config", "libssl-dev"],
	},
	
	go: {
		baseImage: "golang:1.21-alpine",
		depFiles: ["go.mod", "go.sum"],
		installCmd: `
# Download dependencies
COPY go.mod go.sum* ./
RUN go mod download
`,
		testCmd: "go test ./...",
		runtimeDeps: ["git"],
	},
};

export async function generateDockerfile(config: DockerfileConfig): Promise<GeneratedDockerfile> {
	const spec = LANGUAGE_SPECS[config.language] || LANGUAGE_SPECS.python;
	const baseImage = config.baseImage || spec.baseImage;
	
	const dockerfile = `# Generated by pi-collective
# This Dockerfile recreates the project state at the start of a trajectory
#
# Build: docker build -t trajectory-env .
# Run:   docker run -it trajectory-env
# Test:  docker run trajectory-env ${config.testCommand}

FROM ${baseImage}

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    ${(spec.runtimeDeps || ["git"]).join(" \\\n    ")} \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

# Clone repository at specific commit
RUN git clone ${config.repoUrl} . && \\
    git checkout ${config.commitSha}

${spec.installCmd}

# Copy the full source (after deps for better caching if rebuilding)
# This is redundant with git clone but ensures we have exactly what was there
COPY . .

# Set up environment
ENV CI=true
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Default command runs tests
CMD ["sh", "-c", "${config.testCommand}"]

# Labels for traceability
LABEL org.opencontainers.image.source="${config.repoUrl}"
LABEL org.opencontainers.image.revision="${config.commitSha}"
LABEL pi-collective.trajectory="true"
`;

	const dockerignore = `# Generated by pi-collective
.git
.gitignore
*.pyc
__pycache__
.pytest_cache
.mypy_cache
.ruff_cache
node_modules
target
dist
build
*.egg-info
.env
.env.*
.venv
venv
*.log
.DS_Store
`;

	const readme = `# Trajectory Environment

This directory contains a Dockerfile that recreates the exact project state
at the start of a pi-collective trajectory.

## Quick Start

\`\`\`bash
# Build the image
docker build -t trajectory-env .

# Run tests (verifies the environment works)
docker run trajectory-env

# Interactive shell
docker run -it trajectory-env /bin/bash
\`\`\`

## What This Does

1. Starts from \`${baseImage}\`
2. Clones \`${config.repoUrl}\`
3. Checks out commit \`${config.commitSha}\`
4. Installs dependencies
5. Runs \`${config.testCommand}\` by default

## Using for RL Training

This environment can be used with:
- **Prime RL**: Mount as a verifier environment
- **Tinker**: Use as sandbox backend
- **Custom GRPO**: Run tests to compute rewards

## Source

- Repository: ${config.repoUrl}
- Commit: ${config.commitSha}
- Language: ${config.language}
- Test command: ${config.testCommand}
`;

	return { dockerfile, dockerignore, readme };
}

/**
 * Auto-detect language and generate Dockerfile from project directory
 */
export async function generateDockerfileFromProject(
	cwd: string,
	repoUrl: string,
	commitSha: string,
	testCommand?: string
): Promise<GeneratedDockerfile | null> {
	// Detect language
	const language = await detectLanguage(cwd);
	if (!language) {
		return null;
	}
	
	// Detect or use provided test command
	const detectedTestCmd = testCommand || await detectTestCommand(cwd, language);
	if (!detectedTestCmd) {
		return null;
	}
	
	return generateDockerfile({
		repoUrl,
		commitSha,
		language,
		testCommand: detectedTestCmd,
	});
}

async function detectLanguage(cwd: string): Promise<string | null> {
	const indicators: [string, string][] = [
		["pyproject.toml", "python"],
		["requirements.txt", "python"],
		["setup.py", "python"],
		["package.json", "typescript"], // Will refine below
		["Cargo.toml", "rust"],
		["go.mod", "go"],
	];
	
	for (const [file, lang] of indicators) {
		try {
			await access(join(cwd, file));
			
			// Refine JS vs TS
			if (lang === "typescript") {
				try {
					await access(join(cwd, "tsconfig.json"));
					return "typescript";
				} catch {
					return "javascript";
				}
			}
			
			return lang;
		} catch {
			continue;
		}
	}
	
	return null;
}

async function detectTestCommand(cwd: string, language: string): Promise<string | null> {
	switch (language) {
		case "python":
			// Check for pytest
			try {
				const pyproject = await readFile(join(cwd, "pyproject.toml"), "utf-8");
				if (pyproject.includes("pytest")) {
					return "pytest";
				}
			} catch {}
			
			try {
				const requirements = await readFile(join(cwd, "requirements.txt"), "utf-8");
				if (requirements.includes("pytest")) {
					return "pytest";
				}
			} catch {}
			
			// Check for tests directory
			try {
				await access(join(cwd, "tests"));
				return "pytest tests/";
			} catch {}
			
			return "python -m pytest";
			
		case "typescript":
		case "javascript":
			try {
				const pkg = JSON.parse(await readFile(join(cwd, "package.json"), "utf-8"));
				if (pkg.scripts?.test && !pkg.scripts.test.includes("no test specified")) {
					return "npm test";
				}
			} catch {}
			return null;
			
		case "rust":
			return "cargo test";
			
		case "go":
			return "go test ./...";
			
		default:
			return null;
	}
}

/**
 * Generate a minimal Dockerfile that just clones and sets up
 * (doesn't require source files to be present)
 */
export function generateStandaloneDockerfile(config: DockerfileConfig): string {
	const spec = LANGUAGE_SPECS[config.language] || LANGUAGE_SPECS.python;
	const baseImage = config.baseImage || spec.baseImage;
	
	return `# Generated by pi-collective
# Standalone Dockerfile - clones repo directly, no local files needed
#
# Build: docker build -t trajectory-env .
# Test:  docker run trajectory-env

FROM ${baseImage}

# Install git and other deps
RUN apt-get update && apt-get install -y --no-install-recommends \\
    ${(spec.runtimeDeps || ["git"]).join(" \\\n    ")} \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

# Clone and checkout specific commit
RUN git clone ${config.repoUrl} . && \\
    git checkout ${config.commitSha}

# Install project dependencies
${spec.installCmd.replace(/COPY .*/g, "# (dependencies from cloned repo)")}

# Environment
ENV CI=true

# Run tests
CMD ["sh", "-c", "${config.testCommand}"]

LABEL org.opencontainers.image.source="${config.repoUrl}"
LABEL org.opencontainers.image.revision="${config.commitSha}"
`;
}
